export const AGENT_CIRCUIT_BREAKER_COOLDOWN_MS = 60_000;
export const AGENT_CIRCUIT_BREAKER_FAILURE_THRESHOLD = 3;
export const AGENT_COST_LIMIT_USD = 0.05;
export const AGENT_FALLBACK_COST_PER_1K_TOKENS_USD = 0.002;
export const AGENT_MAX_ITERATIONS = 6;
export const AGENT_TIMEOUT_MS = 15_000;
